package com.construe.waterflowcalc.entity

enum class StructureShape {
    CIRCLE_CULVERT,
    BOX_CULVERT,
    TRAPEZOID_CULVERT,
    TRIANGLE_CHANNEL,
    RECTANGLE_CHANNEL,
    TRAPEZOID_CHANNEL,
    SEMICIRCULAR_CHANNEL
}

enum class Roughness(val roughness: Double) {
    POLYETHYLEN_CORRUGATED_INNER_SMOOTH(0.012),
    POLYETHYLEN_CORRUGATED_INNER_CORRUGATED(0.021),
    PVC(0.010),
    ASBESTOS_CEMENT(0.011),
    CAST_IRON(0.012),
    CERAMIC(0.014),
    REINFORCED_CONCRETE(0.011),
    CONCRETE(0.012),
    STEEL(0.012),
    STEEL_INTERNALLY_ENAMELED(0.010),
    CORRUGATED_METAL(0.022),
    GLASS(0.010),
    LEAD(0.011),
    BRASS(0.011),
    COPPER(0.011),
    PLASTIC(0.009)
}

